### ISSUE TITLE
No permission to access data link

### ISSUE THREAD

**Issue by yanghoonkim** [freesunshine0316/MPQG#1]
I found that the data link isn't available.

**Comment by freesunshine0316** [comment]
Thanks. It can be downloaded now.

**Comment by yanghoonkim** [comment]
Is the provided data the split of Du et al. ?

**Comment by freesunshine0316** [comment]
Yeah, I can't directly use the data extracted by Du et al, as their data doesn't have the target answer information. Mine is according to the doclists: https://github.com/xinyadu/nqg/tree/master/data

**Comment by yanghoonkim** [comment]
Yep, However, I found that some of sentences in the data is blank, and I'm using it simply removing them.
