### ISSUE TITLE
Can not find pythonrouge.pythonrouge

### ISSUE THREAD

**Issue by cz3344** [freesunshine0316/MPQG#3]
Hi Freesunshine,
Where can I get `pythonrouge.pythonrouge`? I can not find it by pip install or conda install.
Btw, is it possible to package your environment and create a docker image to help us reproduce your work since   I encountered issue 

> ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory

after I installed tensorflow 1.4.1 . I am try tf1.12 right now but still facing missing module like `pythonrouge` . Thus is it possible to publish a docker image with the required environment? Or at least tell us how to install those dependencies. 

Thank you very much.

**Comment by freesunshine0316** [comment]
Hi,
Did you try install it from https://github.com/tagucci/pythonrouge?

**Comment by cz3344** [comment]
@freesunshine0316 Hi Freesunshine. Yes, I installed pythonrouge while I encountered

> tensorflow.python.framework.errors_impl.InternalError: cudaGetDevice() failed. Status: CUDA driver version is insufficient for CUDA runtime version

**Comment by freesunshine0316** [comment]
It seems that your CUDA library is old. I'm now using TF 1.8 with CUDA 9.0 and CuDNN 9.0.

**Comment by cz3344** [comment]
@freesunshine0316  Hi Freesunshine, thank you for your reply. Do u mean that your code runs perfectly with TF1.8+CUDA9.0+CuDNN9.0? Btw, does it really use GPU or need other settings. Since I found it no GPU is occupied while training.
<img width="1277" alt="screenshot 2018-11-28 11 36 31" src="https://user-images.githubusercontent.com/26409810/49127192-659b6600-f301-11e8-97f0-a92bb6904f85.png">

**Comment by freesunshine0316** [comment]
That's wired. There's even no GPU memory being taken. In my experiments, it definitely takes GPUs.

**Comment by cz3344** [comment]
@freesunshine0316  Yes. It's strange. Does the log file look fine？ how long does 100 training loops take？

**Comment by freesunshine0316** [comment]
That's from my server during training, and it takes 1267.089 seconds to train for 358 steps. The GPU is Tesla K80. 

+-------------------------------+----------------------+----------------------+
|   7  Tesla K80                       Off  | 00000000:1A:00.0 Off |                                0 |
| N/A   59C    P0    140W / 149W |  10953MiB / 11439MiB |       100%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                                           GPU Memory |
|  GPU       PID   Type   Process name                                                        Usage      |
|========================================================|
|    7                            26592                C   python                                     10940MiB |
+-----------------------------------------------------------------------------+

**Comment by cz3344** [comment]
@freesunshine0316 I c. Btw, ur script is python2 or 3?

**Comment by freesunshine0316** [comment]
python2
