### ISSUE TITLE
How to evaluate the results generated by NP2P_beam_decoder.py

### ISSUE THREAD

**Issue by cz3344** [freesunshine0316/MPQG#4]
Hi Freesunshine0316, how to evaluate the results generated by NP2P_beam_decoder.py

**Comment by freesunshine0316** [comment]
I uploaded some scripts into this repository, please refer to them

**Comment by cz3344** [comment]
@freesunshine0316  Hi,  it seems that the uploaded scripts are note related to the evaluation?

**Comment by cz3344** [comment]
@freesunshine0316  Btw, many thx to ur prompt reply！

**Comment by cz3344** [comment]
`python src/NP2P_trainer.py --config_path logs/NP2P.sota.config.json`
Can u also upload the file "logs/NP2P.sota.config.json"? 

I'm a layman in this area. Please don't feel upset if I ask silly questions.

**Comment by freesunshine0316** [comment]
I think you have trained you own model, so you need to modify "logs/NP2P.sota.config.json" to "logs/NP2P.XXX.config.json", where XXX corresponds to your model in "./logs"

**Comment by cz3344** [comment]
Yes. I trained my own model. And I got `logs/NP2P.mpqg_5.config.json`. In addition, the trained model generated questions by beam_decoder.py. 
<img width="1230" alt="screenshot 2018-12-18 20 44 00" src="https://user-images.githubusercontent.com/26409810/50154978-ce28a200-0305-11e9-8f7a-9b38bcef645f.png">

How can I evaluate the output to get the performance similar to the paper reported?

**Comment by freesunshine0316** [comment]
I committed my evaluation script in logs, but you have to modify it to make it work.
